#ruby on rails country data seed.

Country.create(country_code: 'AF', name: 'Afghanistan')
Country.create(country_code: 'AL', name: 'Albania')
Country.create(country_code: 'DZ', name: 'Algeria')
Country.create(country_code: 'DS', name: 'American Samoa')
Country.create(country_code: 'AD', name: 'Andorra')
Country.create(country_code: 'AO', name: 'Angola')
Country.create(country_code: 'AI', name: 'Anguilla')
Country.create(country_code: 'AQ', name: 'Antarctica')
Country.create(country_code: 'AG', name: 'Antigua and/or Barbuda')
Country.create(country_code: 'AR', name: 'Argentina')
Country.create(country_code: 'AM', name: 'Armenia')
Country.create(country_code: 'AW', name: 'Aruba')
Country.create(country_code: 'AU', name: 'Australia')
Country.create(country_code: 'AT', name: 'Austria')
Country.create(country_code: 'AZ', name: 'Azerbaijan')
Country.create(country_code: 'BS', name: 'Bahamas')
Country.create(country_code: 'BH', name: 'Bahrain')
Country.create(country_code: 'BD', name: 'Bangladesh')
Country.create(country_code: 'BB', name: 'Barbados')
Country.create(country_code: 'BY', name: 'Belarus')
Country.create(country_code: 'BE', name: 'Belgium')
Country.create(country_code: 'BZ', name: 'Belize')
Country.create(country_code: 'BJ', name: 'Benin')
Country.create(country_code: 'BM', name: 'Bermuda')
Country.create(country_code: 'BT', name: 'Bhutan')
Country.create(country_code: 'BO', name: 'Bolivia')
Country.create(country_code: 'BA', name: 'Bosnia and Herzegovina')
Country.create(country_code: 'BW', name: 'Botswana')
Country.create(country_code: 'BV', name: 'Bouvet Island')
Country.create(country_code: 'BR', name: 'Brazil')
Country.create(country_code: 'IO', name: 'British Indian Ocean Territory')
Country.create(country_code: 'BN', name: 'Brunei Darussalam')
Country.create(country_code: 'BG', name: 'Bulgaria')
Country.create(country_code: 'BF', name: 'Burkina Faso')
Country.create(country_code: 'BI', name: 'Burundi')
Country.create(country_code: 'KH', name: 'Cambodia')
Country.create(country_code: 'CM', name: 'Cameroon')
Country.create(country_code: 'CA', name: 'Canada')
Country.create(country_code: 'CV', name: 'Cape Verde')
Country.create(country_code: 'KY', name: 'Cayman Islands')
Country.create(country_code: 'CF', name: 'Central African Republic')
Country.create(country_code: 'TD', name: 'Chad')
Country.create(country_code: 'CL', name: 'Chile')
Country.create(country_code: 'CN', name: 'China')
Country.create(country_code: 'CX', name: 'Christmas Island')
Country.create(country_code: 'CC', name: 'Cocos (Keeling) Islands')
Country.create(country_code: 'CO', name: 'Colombia')
Country.create(country_code: 'KM', name: 'Comoros')
Country.create(country_code: 'CG', name: 'Congo')
Country.create(country_code: 'CK', name: 'Cook Islands')
Country.create(country_code: 'CR', name: 'Costa Rica')
Country.create(country_code: 'HR', name: 'Croatia (Hrvatska)')
Country.create(country_code: 'CU', name: 'Cuba')
Country.create(country_code: 'CY', name: 'Cyprus')
Country.create(country_code: 'CZ', name: 'Czech Republic')
Country.create(country_code: 'DK', name: 'Denmark')
Country.create(country_code: 'DJ', name: 'Djibouti')
Country.create(country_code: 'DM', name: 'Dominica')
Country.create(country_code: 'DO', name: 'Dominican Republic')
Country.create(country_code: 'TP', name: 'East Timor')
Country.create(country_code: 'EC', name: 'Ecuador')
Country.create(country_code: 'EG', name: 'Egypt')
Country.create(country_code: 'SV', name: 'El Salvador')
Country.create(country_code: 'GQ', name: 'Equatorial Guinea')
Country.create(country_code: 'ER', name: 'Eritrea')
Country.create(country_code: 'EE', name: 'Estonia')
Country.create(country_code: 'ET', name: 'Ethiopia')
Country.create(country_code: 'FK', name: 'Falkland Islands (Malvinas)')
Country.create(country_code: 'FO', name: 'Faroe Islands')
Country.create(country_code: 'FJ', name: 'Fiji')
Country.create(country_code: 'FI', name: 'Finland')
Country.create(country_code: 'FR', name: 'France')
Country.create(country_code: 'FX', name: 'France, Metropolitan')
Country.create(country_code: 'GF', name: 'French Guiana')
Country.create(country_code: 'PF', name: 'French Polynesia')
Country.create(country_code: 'TF', name: 'French Southern Territories')
Country.create(country_code: 'GA', name: 'Gabon')
Country.create(country_code: 'GM', name: 'Gambia')
Country.create(country_code: 'GE', name: 'Georgia')
Country.create(country_code: 'DE', name: 'Germany')
Country.create(country_code: 'GH', name: 'Ghana')
Country.create(country_code: 'GI', name: 'Gibraltar')
Country.create(country_code: 'GK', name: 'Guernsey')
Country.create(country_code: 'GR', name: 'Greece')
Country.create(country_code: 'GL', name: 'Greenland')
Country.create(country_code: 'GD', name: 'Grenada')
Country.create(country_code: 'GP', name: 'Guadeloupe')
Country.create(country_code: 'GU', name: 'Guam')
Country.create(country_code: 'GT', name: 'Guatemala')
Country.create(country_code: 'GN', name: 'Guinea')
Country.create(country_code: 'GW', name: 'Guinea-Bissau')
Country.create(country_code: 'GY', name: 'Guyana')
Country.create(country_code: 'HT', name: 'Haiti')
Country.create(country_code: 'HM', name: 'Heard and Mc Donald Islands')
Country.create(country_code: 'HN', name: 'Honduras')
Country.create(country_code: 'HK', name: 'Hong Kong')
Country.create(country_code: 'HU', name: 'Hungary')
Country.create(country_code: 'IS', name: 'Iceland')
Country.create(country_code: 'IN', name: 'India')
Country.create(country_code: 'IM', name: 'Isle of Man')
Country.create(country_code: 'ID', name: 'Indonesia')
Country.create(country_code: 'IR', name: 'Iran (Islamic Republic of)')
Country.create(country_code: 'IQ', name: 'Iraq')
Country.create(country_code: 'IE', name: 'Ireland')
Country.create(country_code: 'IL', name: 'Israel')
Country.create(country_code: 'IT', name: 'Italy')
Country.create(country_code: 'CI', name: 'Ivory Coast')
Country.create(country_code: 'JE', name: 'Jersey')
Country.create(country_code: 'JM', name: 'Jamaica')
Country.create(country_code: 'JP', name: 'Japan')
Country.create(country_code: 'JO', name: 'Jordan')
Country.create(country_code: 'KZ', name: 'Kazakhstan')
Country.create(country_code: 'KE', name: 'Kenya')
Country.create(country_code: 'KI', name: 'Kiribati')
Country.create(country_code: 'KP', name: 'Korea, Democratic People''s Republic of')
Country.create(country_code: 'KR', name: 'Korea, Republic of')
Country.create(country_code: 'XK', name: 'Kosovo')
Country.create(country_code: 'KW', name: 'Kuwait')
Country.create(country_code: 'KG', name: 'Kyrgyzstan')
Country.create(country_code: 'LA', name: 'Lao People''s Democratic Republic')
Country.create(country_code: 'LV', name: 'Latvia')
Country.create(country_code: 'LB', name: 'Lebanon')
Country.create(country_code: 'LS', name: 'Lesotho')
Country.create(country_code: 'LR', name: 'Liberia')
Country.create(country_code: 'LY', name: 'Libyan Arab Jamahiriya')
Country.create(country_code: 'LI', name: 'Liechtenstein')
Country.create(country_code: 'LT', name: 'Lithuania')
Country.create(country_code: 'LU', name: 'Luxembourg')
Country.create(country_code: 'MO', name: 'Macau')
Country.create(country_code: 'MK', name: 'Macedonia')
Country.create(country_code: 'MG', name: 'Madagascar')
Country.create(country_code: 'MW', name: 'Malawi')
Country.create(country_code: 'MY', name: 'Malaysia')
Country.create(country_code: 'MV', name: 'Maldives')
Country.create(country_code: 'ML', name: 'Mali')
Country.create(country_code: 'MT', name: 'Malta')
Country.create(country_code: 'MH', name: 'Marshall Islands')
Country.create(country_code: 'MQ', name: 'Martinique')
Country.create(country_code: 'MR', name: 'Mauritania')
Country.create(country_code: 'MU', name: 'Mauritius')
Country.create(country_code: 'TY', name: 'Mayotte')
Country.create(country_code: 'MX', name: 'Mexico')
Country.create(country_code: 'FM', name: 'Micronesia, Federated States of')
Country.create(country_code: 'MD', name: 'Moldova, Republic of')
Country.create(country_code: 'MC', name: 'Monaco')
Country.create(country_code: 'MN', name: 'Mongolia')
Country.create(country_code: 'ME', name: 'Montenegro')
Country.create(country_code: 'MS', name: 'Montserrat')
Country.create(country_code: 'MA', name: 'Morocco')
Country.create(country_code: 'MZ', name: 'Mozambique')
Country.create(country_code: 'MM', name: 'Myanmar')
Country.create(country_code: 'NA', name: 'Namibia')
Country.create(country_code: 'NR', name: 'Nauru')
Country.create(country_code: 'NP', name: 'Nepal')
Country.create(country_code: 'NL', name: 'Netherlands')
Country.create(country_code: 'AN', name: 'Netherlands Antilles')
Country.create(country_code: 'NC', name: 'New Caledonia')
Country.create(country_code: 'NZ', name: 'New Zealand')
Country.create(country_code: 'NI', name: 'Nicaragua')
Country.create(country_code: 'NE', name: 'Niger')
Country.create(country_code: 'NG', name: 'Nigeria')
Country.create(country_code: 'NU', name: 'Niue')
Country.create(country_code: 'NF', name: 'Norfolk Island')
Country.create(country_code: 'MP', name: 'Northern Mariana Islands')
Country.create(country_code: 'NO', name: 'Norway')
Country.create(country_code: 'OM', name: 'Oman')
Country.create(country_code: 'PK', name: 'Pakistan')
Country.create(country_code: 'PW', name: 'Palau')
Country.create(country_code: 'PS', name: 'Palestine')
Country.create(country_code: 'PA', name: 'Panama')
Country.create(country_code: 'PG', name: 'Papua New Guinea')
Country.create(country_code: 'PY', name: 'Paraguay')
Country.create(country_code: 'PE', name: 'Peru')
Country.create(country_code: 'PH', name: 'Philippines')
Country.create(country_code: 'PN', name: 'Pitcairn')
Country.create(country_code: 'PL', name: 'Poland')
Country.create(country_code: 'PT', name: 'Portugal')
Country.create(country_code: 'PR', name: 'Puerto Rico')
Country.create(country_code: 'QA', name: 'Qatar')
Country.create(country_code: 'RE', name: 'Reunion')
Country.create(country_code: 'RO', name: 'Romania')
Country.create(country_code: 'RU', name: 'Russian Federation')
Country.create(country_code: 'RW', name: 'Rwanda')
Country.create(country_code: 'KN', name: 'Saint Kitts and Nevis')
Country.create(country_code: 'LC', name: 'Saint Lucia')
Country.create(country_code: 'VC', name: 'Saint Vincent and the Grenadines')
Country.create(country_code: 'WS', name: 'Samoa')
Country.create(country_code: 'SM', name: 'San Marino')
Country.create(country_code: 'ST', name: 'Sao Tome and Principe')
Country.create(country_code: 'SA', name: 'Saudi Arabia')
Country.create(country_code: 'SN', name: 'Senegal')
Country.create(country_code: 'RS', name: 'Serbia')
Country.create(country_code: 'SC', name: 'Seychelles')
Country.create(country_code: 'SL', name: 'Sierra Leone')
Country.create(country_code: 'SG', name: 'Singapore')
Country.create(country_code: 'SK', name: 'Slovakia')
Country.create(country_code: 'SI', name: 'Slovenia')
Country.create(country_code: 'SB', name: 'Solomon Islands')
Country.create(country_code: 'SO', name: 'Somalia')
Country.create(country_code: 'ZA', name: 'South Africa')
Country.create(country_code: 'GS', name: 'South Georgia South Sandwich Islands')
Country.create(country_code: 'ES', name: 'Spain')
Country.create(country_code: 'LK', name: 'Sri Lanka')
Country.create(country_code: 'SH', name: 'St. Helena')
Country.create(country_code: 'PM', name: 'St. Pierre and Miquelon')
Country.create(country_code: 'SD', name: 'Sudan')
Country.create(country_code: 'SR', name: 'Suriname')
Country.create(country_code: 'SJ', name: 'Svalbard and Jan Mayen Islands')
Country.create(country_code: 'SZ', name: 'Swaziland')
Country.create(country_code: 'SE', name: 'Sweden')
Country.create(country_code: 'CH', name: 'Switzerland')
Country.create(country_code: 'SY', name: 'Syrian Arab Republic')
Country.create(country_code: 'TW', name: 'Taiwan')
Country.create(country_code: 'TJ', name: 'Tajikistan')
Country.create(country_code: 'TZ', name: 'Tanzania, United Republic of')
Country.create(country_code: 'TH', name: 'Thailand')
Country.create(country_code: 'TG', name: 'Togo')
Country.create(country_code: 'TK', name: 'Tokelau')
Country.create(country_code: 'TO', name: 'Tonga')
Country.create(country_code: 'TT', name: 'Trinidad and Tobago')
Country.create(country_code: 'TN', name: 'Tunisia')
Country.create(country_code: 'TR', name: 'Turkey')
Country.create(country_code: 'TM', name: 'Turkmenistan')
Country.create(country_code: 'TC', name: 'Turks and Caicos Islands')
Country.create(country_code: 'TV', name: 'Tuvalu')
Country.create(country_code: 'UG', name: 'Uganda')
Country.create(country_code: 'UA', name: 'Ukraine')
Country.create(country_code: 'AE', name: 'United Arab Emirates')
Country.create(country_code: 'GB', name: 'United Kingdom')
Country.create(country_code: 'US', name: 'United States')
Country.create(country_code: 'UM', name: 'United States minor outlying islands')
Country.create(country_code: 'UY', name: 'Uruguay')
Country.create(country_code: 'UZ', name: 'Uzbekistan')
Country.create(country_code: 'VU', name: 'Vanuatu')
Country.create(country_code: 'VA', name: 'Vatican City State')
Country.create(country_code: 'VE', name: 'Venezuela')
Country.create(country_code: 'VN', name: 'Vietnam')
Country.create(country_code: 'VG', name: 'Virgin Islands (British)')
Country.create(country_code: 'VI', name: 'Virgin Islands (U.S.)')
Country.create(country_code: 'WF', name: 'Wallis and Futuna Islands')
Country.create(country_code: 'EH', name: 'Western Sahara')
Country.create(country_code: 'YE', name: 'Yemen')
Country.create(country_code: 'YU', name: 'Yugoslavia')
Country.create(country_code: 'ZR', name: 'Zaire')
Country.create(country_code: 'ZM', name: 'Zambia')
Country.create(country_code: 'ZW', name: 'Zimbabwe')
